---

- name: 生成阿里云提供商相关配置
  block:
  - name: 创建阿里云部署相关目录
    file: path={{ item }} mode=0755 state=directory
    with_items:
      - "{{ etc_dir }}/addons/kube-system/cloud_provider/{{ cloud_provider }}"

  - name: 创建 cloud-controller-manager kubeconfig 文件
    template:
      src: "kubeconfig/{{ item }}.j2"
      dest: /etc/kubernetes/{{ item }}
      owner: "{{ kube_user.name }}"
      group: root
      mode: 0600
    with_items:
      - cloud-controller-manager.conf

  - name: 创建 cloud-controller-manager 部署清单
    template:
      src: addons/kube-system/cloud_provider/{{ cloud_provider }}/{{ item }}.j2
      dest: "{{ etc_dir }}/addons/kube-system/cloud_provider/{{ cloud_provider }}/{{ item }}"
      owner: "{{ kube_user.name }}"
      group: root
      mode: 0644
    with_items:
      - cloud-controller-manager.yaml

  when: cloud_provider == "alibaba-cloud"
