---
- name: 创建 kube-apiserver 配置文件
  template:
    src: kube-apiserver/environment.j2
    dest: "{{ install_dir }}/kube-apiserver/environment"
    owner: root
    group: root
    mode: 0644
    backup: no

- name: 创建审计规则文件
  template:
    src: kube-apiserver/audit-policy.yaml.j2
    dest: "{{ install_dir }}/kube-apiserver/audit-policy.yaml"
    owner: root
    group: root
    mode: 0644
    backup: no

- name: 创建 admin.config 文件
  template:
    src: kube-apiserver/admin.conf.j2
    dest: "{{ etc_dir }}/admin.conf"
    owner: root
    group: root
    mode: 0600
    backup: no

# 拷贝 kube-apiserver 二进制文件
- stat: 
    path: "{{ install_dir }}/kube-apiserver/kube-apiserver"
  register: apiserver
- name: 拷贝 kube-apiserver 二进制文件
  copy:
    src: ../../binary/files/kubernetes/server/bin/kube-apiserver
    dest: "{{ install_dir }}/kube-apiserver/kube-apiserver"
    owner: root
    group: root
    mode: 0755
  when: apiserver.stat.exists == False

# 创建静态token文件（用于kubelet-bootstrap）格式：token,user,uid,"group1,group2,group3"
# 拥有token，既可使用user或group1、group2、group3的权限
- name: 创建 known_tokens.csv 文件
  template:
    src=known_tokens.csv.j2 dest={{ etc_dir }}/known_tokens.csv owner=root group=root mode=0644

- name: 创建 kube-apiserver systemd 文件
  template:
    src: kube-apiserver/kube-apiserver.service.j2
    dest: /usr/lib/systemd/system/kube-apiserver.service
    owner: root
    group: root
    mode: 0644
    backup: no
  notify:
    - enabled kube-apiserver
    - restart kube-apiserver
