---

# 创建 kubeadm 相关目录
- name: 创建 kubeadm 相关目录
  file: path={{ item }} mode=0755 state=directory
  with_items:
    - "{{ etc_dir }}/kubeadm"
    - "{{ etc_dir }}/kubeadm/patches"

- name: 创建 kubeadm config.yaml
  template:
    src: kubeadm/config.yaml.j2
    dest: "{{ etc_dir }}/kubeadm/config.yaml"
    owner: "{{ kube_user.name }}"
    group: root
    mode: 0644

- name: 创建 kubeadm control patches
  template:
    src: "kubeadm/patches/{{ item }}.j2"
    dest: "{{ etc_dir }}/kubeadm/patches/{{ item }}"
    owner: "{{ kube_user.name }}"
    group: root
    mode: 0644
  with_items:
    - kube-apiserver+merge.yaml

# https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/
- name: 创建 kube-scheduler 配置文件
  template:
    src: kube-scheduler/config.yaml.j2
    dest: "{{ etc_dir }}/scheduler-config.yaml"
    owner: "{{ kube_user.name }}"
    group: root
    mode: 0644
    backup: no

# 创建静态token文件（用于kubelet-bootstrap）格式：token,user,uid,"group1,group2,group3"
# 拥有token，既可使用user或group1、group2、group3的权限
- name: 创建 known_tokens.csv 文件
  template:
    src: kube-apiserver/known_tokens.csv.j2
    dest: "{{ etc_dir }}/known_tokens.csv"
    owner: "{{ kube_user.name }}"
    group: root
    mode: 0644

- name: 创建审计规则文件
  template:
    src: kube-apiserver/audit-policy.yaml.j2
    dest: "{{ etc_dir }}/audit-policy.yaml"
    owner: "{{ kube_user.name }}"
    group: root
    mode: 0644
    backup: no

# 同步静态pod文件
- name: 创建静态POD文件
  template:
    src: "manifests/{{ item }}.j2"
    dest: /etc/kubernetes/manifests/{{ item }}
    owner: root
    group: root
    mode: 0600
  with_items:
    - etcd.yaml
    - kube-apiserver.yaml
    - kube-controller-manager.yaml
    - kube-scheduler.yaml

- name: 同步 kube-apiserver 策略相关文件
  template:
    src: "policies/{{ item }}.j2"
    dest: /etc/kubernetes/policies/{{ item }}
    owner: root
    group: root
    mode: 0600
  with_items:
    - admission-controls.yaml

- name: 创建 kubeconfig admin.conf 文件
  template:
    src: "kubeconfig/{{ item }}.j2"
    dest: /etc/kubernetes/{{ item }}
    owner: root
    group: root
    mode: 0600
  with_items:
    - admin.conf

- name: 创建 kubeconfig 其他文件
  template:
    src: "kubeconfig/{{ item }}.j2"
    dest: /etc/kubernetes/{{ item }}
    owner: "{{ kube_user.name }}"
    group: root
    mode: 0600
  with_items:
    - kubelet.conf
    - scheduler.conf
    - controller-manager.conf

#- name: 创建 kubelet-client 证书
#  template:
#    src: "kubeconfig/{{ item }}.j2"
#    dest: /etc/kubernetes/{{ item }}
#    owner: root
#    group: root
#    mode: 0644
#  with_items:
#    - 

- name: 创建kubectl授权文件
  template:
    src: kubeconfig/admin.conf.j2
    dest: "/root/.kube/config"
    owner: root
    group: root
    mode: 0600
    backup: no
