---

# 创建 k8s control plane 相关目录
- name: 创建k8s控制平面相关目录
  file: path={{ item }} mode=0755 state=directory
  with_items:
    - /root/.kube
    - /usr/local/src/addons
    - /usr/local/src/addons/calico
    - /usr/local/src/addons/coredns
    - /usr/local/src/addons/kube-proxy
    - /usr/local/src/addons/kube-system
    - /usr/local/src/addons/metrics-server
    - "{{ data_dir }}/kubelet/pki"

- import_tasks: certs.yaml
- import_tasks: addons.yaml
- import_tasks: kubeadm.yaml
