---

# 创建 k8s control plane 相关目录
- name: 创建k8s控制平面相关目录
  file: path={{ item }} mode=0755 state=directory
  with_items:
    - /root/.kube
    - "{{ etc_dir }}/addons"
    - "{{ data_dir }}/kubelet/pki"

- import_tasks: certs.yaml
- import_tasks: addons.yaml
- import_tasks: kubeadm.yaml
- import_tasks: cloud_provider.yaml
