---
- name: kubectl apply manifests
  shell: "kubectl apply -k /usr/local/src/manifests"
  run_once: true
  ignore_errors: yes

- name: kubectl label control
  shell: "kubectl label node {{ hostvars[item]['ansible_host'] }} node-role.kubernetes.io/master="
  run_once: true
  ignore_errors: yes
  loop: "{{ groups['control'] }}"

- name: kubectl label control
  shell: "kubectl taint node {{ hostvars[item]['ansible_host'] }} node-role.kubernetes.io/master:NoSchedule"
  run_once: true
  ignore_errors: yes
  loop: "{{ groups['control'] }}"
