---

- name: kubectl label control
  shell: "kubectl label node {{ hostvars[item]['ip'] }} node-role.kubernetes.io/master="
  run_once: true
  ignore_errors: yes
  loop: "{{ groups['control'] }}"

- name: kubectl label control
  shell: "kubectl taint node {{ hostvars[item]['ip'] }} node-role.kubernetes.io/master:NoSchedule"
  run_once: true
  ignore_errors: yes
  loop: "{{ groups['control'] }}"
