variables:
  GIT_SSL_NO_VERIFY: "true"
  ANSIBLE_FORCE_COLOR: "true"

before_script:
  - 'git lfs pull'
  - 'cd ansible/'
  - 'echo "dynamic inventory: get from cmdb"'

stages:
  - check 
  - deploy

check-job-1:
  stage: check
  script:
    - ansible -i hosts.ini common -m ping
  tags: 
    - dcim-k8s
  only:
    changes:
      - ansible/*

deploy-job-1:
  stage: deploy
  script:
    - ansible-playbook -i hosts.ini deploy.yaml -t pki
  tags: 
    - dcim-k8s
  only:
    changes:
      - ansible/*

deploy-job-2:
  stage: deploy
  script:
    - ansible-playbook -i hosts.ini deploy.yaml -t common
  tags: 
    - dcim-k8s
  only:
    changes:
      - ansible/*

deploy-job-3:
  stage: deploy
  script:
    - ansible-playbook -i hosts.ini deploy.yaml -t control
  tags: 
    - dcim-k8s
  only:
    changes:
      - ansible/*

deploy-job-4:
  stage: deploy
  script:
    - ansible-playbook -i hosts.ini deploy.yaml -t worker
  tags: 
    - dcim-k8s
  only:
    changes:
      - ansible/*
