---

- stat:
    path: roles/pki/files/{{ item }}.crt
  with_items:
  - front-proxy/client
  register: certs
- name: 生成front-proxy相关证书
  vars:
    work_dir: "roles/pki/files"
    cert_kind: "{{ outer_item.item | dirname }}"
    cert_name: "{{ outer_item.item | basename }}"
  include_tasks: "openssl.yaml"
  with_items: "{{ certs.results }}"
  loop_control:
    loop_var: outer_item
  when: outer_item.stat.exists == False
