---
- name: reload systemd
  systemd: daemon_reload=yes
- name: enabled containerd
  systemd: name=containerd enabled=yes state=started
- name: restart containerd
  systemd: name=containerd state=restarted daemon_reload=yes
