---

- name: 运行 etcd 组件用户
  block:
    - name: 创建 {{ etcd_user.name }} 组
      group:
        name: "{{ etcd_user.name }}"
        gid: "{{ etcd_user.id }}"
        system: yes
    - name: 创建 {{ etcd_user.name }} 用户
      user:
        uid: "{{ etcd_user.id }}"
        comment: "Etcd user"
        createhome: no
        group: "{{ etcd_user.name }}"
        shell: /sbin/nologin
        name: "{{ etcd_user.name }}"
        system: yes
  when: etcd_user.name != "root"

- name: 运行控制平面组件用户
  block:
    - name: 创建 {{ kube_user.name }} 组
      group:
        name: "{{ kube_user.name }}"
        gid: "{{ kube_user.id }}"
        system: yes
    - name: 创建 {{ kube_user.name }} 用户
      user:
        uid: "{{ kube_user.id }}"
        comment: "Kubernetes user"
        createhome: no
        group: "{{ kube_user.name }}"
        shell: /sbin/nologin
        name: "{{ kube_user.name }}"
        system: yes
  when: kube_user.name != "root"