---

# 创建 kubernetes 安装目录
- name: 创建 kubernetes 安装目录
  file: 
    path: "{{ item }}" 
    owner: kube 
    group: root 
    mode: 0755 
    state: directory
  with_items:
    - "{{ data_dir }}"
    - "{{ etc_dir }}"
    - "{{ etc_dir }}/pki"
    - "{{ etc_dir }}/pki/etcd"
    - "{{ etc_dir }}/pki/oidc"
    - "{{ etc_dir }}/manifests"
    - "{{ log_dir }}"
    - "{{ install_dir }}"

# 创建etcd相关目录
- name: 创建etcd相关目录
  file: 
    path: "{{ item }}" 
    owner: etcd
    group: etcd
    mode: 0700
    state: directory
  with_items:
    - "{{ data_dir }}/etcd"

# 创建cni相关目录
- name: 创建cni相关目录
  file: 
    path: "{{ item }}" 
    owner: kube
    group: root 
    mode: 0755 
    state: directory
  with_items:
    - /opt/cni/bin
    - /etc/cni/net.d

# 创建 containerd 相关目录
- name: 创建 containerd 相关目录
  file:
    path: "{{ item }}"
    owner: root
    group: root 
    state: directory
  with_items:
    - "{{ data_dir }}/containerd"
    - /opt/containerd
    - /etc/containerd
    - /data/containerd
