---

- name: 设置 /etc/hosts
  block:
    - name: 添加 apiserver 地址 /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ apiserver_haip }} {{ apiserver_host }}"
        regexp: "^{{ apiserver_haip }} {{ apiserver_host }}"
  when: resolv_use_hosts
