---
# 帮助文档地址
product_docs: https://opsaid.cn/docs

# 部署脚本版本
deploy_version: 2.0.0

# 设置节点时区
# /usr/share/zoneinfo/Asia/Shanghai
timezone: Asia/Shanghai

# 对节点通过/etc/hosts做dns条目绑定
resolv_use_hosts: true

# 使用外部的etcd服务，不会实际部署etcd
# 在hosts中配置的etcd地址仅用于设置kube-apiserver的连接
external_etcd: false

# 部署的k8s主版本
k8s_version: 1.18

# k8s组件安装的根目录
install_dir: /usr/local/kubernetes-{{ k8s_version }}

# k8s配置文件目录
etc_dir: /etc/kubernetes

# k8s组件日志目录
log_dir: /var/log/kubernetes

# 存放数据目录
data_dir: /data

# 集群编号与名称
cluster_name: fake

# 集群域名后缀
cluster_domain: "{{ cluster_name }}.k8s.opsaid.cn"

# worker 节点使用的子网掩码
node_cidr_mask: 28

# worker 节点支持的最大 pod 数量
node_max_pods: 32

# 集群pod使用的网络地址范围
cluster_cidr: 192.168.201.0/24

# master cluster ip
master_cluster_ip: 10.233.0.1

# 集群内coredns service地址
cluster_dns: 10.233.0.2

# 集群service使用的网络地址范围
# 可取范围：10.0.0.0/16-24，172.16-31.0.0/16-24，192.168.0.0/16-24
service_cluster_ip_range: 10.233.0.0/16

# 集群南北流量高可用的ip地址
# 一般为vip，没有则设置为控制平面任意一个实际的ip地址
apiserver_haip: 192.168.31.204
# 域名地址对应高可用ip，其他外部服务如有依赖均使用该域名
apiserver_host: "{{ cluster_domain }}"
# 提供给各个客户端连接kube-apiserver且使用tls认证的地址
apiserver_addr: https://{{ apiserver_host }}:6443

# tls bootstrapping, 首次部署生成下token之后无需变更
# 生成方式：head -c 16 /dev/urandom | od -An -t x | tr -d ' '
tls_bootstrap_user: kubelet-bootstrap
tls_bootstrap_token: 53fb9ee737936db263ebd937ab1829cd

# 在系统级禁用ipv6
disable_ipv6: true

# 系统服务是否必须在控制节点
system_service_in_control_node: false

# oidc设置
#oidc_issuer_url: https://opsaid.com/oauth2
#oidc_client_id: kubernetes
#oidc_username_claim: email
#oidc_groups_claim: groups
# 如果是自签ca，则需要把ca文件存放至pki/files/oidc/ca.crt下
#oidc_ca_file: /etc/kubernetes/pki/oidc/ca.crt

# 容器镜像中心，集群只允许以下登记的地址
# 设置 insecure_skip_verify=true 跳过https的ca认证
container_registry:
- mirror: 'docker.io'
  endpoints: [ "https://docker.mirrors.ustc.edu.cn" ]
  tls:
    insecure_skip_verify: true
- mirror: 'registry.cn-hangzhou.aliyuncs.com/kube-image-repo'
  endpoints: [ "https://registry.cn-hangzhou.aliyuncs.com/kube-image-repo" ]
  #auth:
  #  username: ""
  #  password: ""
  tls:
    insecure_skip_verify: true
    
# 内部系统镜像地址，必须存在
internal_images:
  namespace: registry.cn-hangzhou.aliyuncs.com/kube-image-repo
  system:
    sandbox: pause:3.2
    coredns: coredns:1.1.3
    metrics_server: metrics-server-amd64:v0.3.6
  calico:
    cni: calico-cni:v3.16.5
    node: calico-node:v3.16.5
    controller: calico-kube-controllers:v3.16.5

# 预留系统资源，防止节点内存不足导致离线
# 由于swap被关闭，如果可用内存不足，节点会进入不可用状态
resource_reserve:
  kube:
    cpu: 100m
    memory: 100Mi
  system:
    cpu: 50m
    memory: 50Mi

# 是否允许开启swap
disable_swap: false
