---

# 拷贝证书
- name: 拷贝证书
  copy: src=../../pki/files/apiserver/{{ item }} dest={{ etc_dir }}/pki/{{ item }} owner=root group=root mode=0644
  with_items:
    - ca.crt
    - apiserver.crt
    - kube-proxy-client.crt
    - kube-proxy-client.key
