---

# 拷贝证书
- name: 拷贝证书
  copy: 
    src: ../../pki/files/apiserver/{{ item }} 
    dest: "{{ etc_dir }}/pki/{{ item }}"
    mode: 0644
    owner: "{{ kube_user.name }}"
    group: root 
  with_items:
    - ca.crt
    - apiserver.crt
    - kube-proxy-client.crt
- name: 拷贝证书
  copy: 
    src: ../../pki/files/apiserver/{{ item }} 
    dest: "{{ etc_dir }}/pki/{{ item }}"
    mode: 0600
    owner: "{{ kube_user.name }}"
    group: root 
  with_items:
    - kube-proxy-client.key