---
# socat 用于 worker 节点端口转发使用(helm)
# ipvsadm 用于 ProxyMode=lvs 下，管理查看条目方便
- name: 安装基础软件包
  yum: 
    name: ['socat', 'ipvsadm'] 
    state: latest

- name: 创建 kube-proxy 配置文件
  template:
    src: kube-proxy/{{ item }}.j2
    dest: "{{ install_dir }}/kube-proxy/{{ item }}"
    owner: root
    group: root
    mode: 0644
    backup: no
  with_items:
    - config.yaml
    - environment
  notify:
    - restart kube-proxy

- name: 创建 kube-proxy kubeconfig配置文件
  template:
    src: kube-proxy/{{ item }}.j2
    dest: "{{ etc_dir }}/{{ item }}"
    owner: root
    group: root
    mode: 0644
    backup: no
  with_items:
    - kube-proxy.conf
  notify:
    - restart kube-proxy

# 拷贝证书
- name: 拷贝证书
  copy: src=../../pki/files/apiserver/{{ item }} dest={{ etc_dir }}/pki/{{ item }} owner=root group=root mode=0644
  with_items:
    - apiserver.crt
    - kube-proxy-client.crt
    - kube-proxy-client.key

# 拷贝 kube-proxy 二进制文件
- stat:
    path: "{{ install_dir }}/kube-proxy/kube-proxy"
  register: proxy
- name: 拷贝 kube-proxy 二进制文件
  copy:
    src: ../../binary/files/kubernetes/server/bin/kube-proxy
    dest: "{{ install_dir }}/kube-proxy/kube-proxy"
    owner: root
    group: root
    mode: 0755
  when: proxy.stat.exists == False

- name: 创建 kube-proxy systemd 文件
  template:
    src: kube-proxy/kube-proxy.service.j2
    dest: /usr/lib/systemd/system/kube-proxy.service
    owner: root
    group: root
    mode: 0644
    backup: no
  notify:
    - enabled kube-proxy
    - restart kube-proxy
