---
# 创建 k8s worker 相关目录
- name: 创建 k8s worker 相关目录
  file: path={{ item }} mode=0755 state=directory
  with_items:
    - "{{ install_dir }}"
    - "{{ data_dir }}/kubelet"
    - "{{ etc_dir }}/manifests"
    - "/etc/systemd/system/kubelet.service.d"

- import_tasks: certs.yaml
- import_tasks: kubelet.yaml
- import_tasks: kubectl.yaml
- import_tasks: kubeadm.yaml
- import_tasks: calicoctl.yaml
  when: network_plugin == "calico"
