---

- name: 生成集群依赖的证书至部署仓库
  hosts: pki
  remote_user: root
  tags:
  - pki
  roles:
  - pki
  vars_files:
  - group_vars/default.yaml

- name: 下载依赖的二进制文件至部署仓库
  hosts: binary
  remote_user: root
  tags:
  - binary
  roles:
  - binary
  vars_files:
  - group_vars/default.yaml
  - group_vars/component-v{{ k8s_version.split('.')[:2] | join('.') }}.yaml

- name: 针对所有节点实现公共基础配置
  hosts: kube_control_plane,kube_node
  remote_user: root
  tags:
  - common
  roles:
  - common
  vars_files:
  - group_vars/default.yaml

- name: 部署K8S控制平面节点
  hosts: kube_control_plane
  remote_user: root
  tags:
  - control
  roles:
  - control
  - runtime
  - node
  vars_files:
  - group_vars/default.yaml
  - group_vars/component-v{{ k8s_version.split('.')[:2] | join('.') }}.yaml

- name: 部署K8S工作负载节点
  hosts: kube_node
  remote_user: root
  tags:
  - worker
  roles:
  - runtime
  - node
  vars_files:
  - group_vars/default.yaml
  - group_vars/component-v{{ k8s_version.split('.')[:2] | join('.') }}.yaml

- name: 卸载节点
  hosts: uninstall
  remote_user: root
  tags:
  - uninstall
  roles:
  - uninstall
  vars_files:
  - group_vars/default.yaml
