apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo

#configMapGenerator:
#- name: workflow-controller-configmap
#  files:
#  - controller-config.yaml=config/configmap/controller-config.yaml
#  options:
#    disableNameSuffixHash: true

replicas:
- name: argo-server
  count: 1
- name: workflow-controller
  count: 1

resources:
- cluster/crds.yaml
- cluster/roles.yaml
- cluster/namespace.yaml
- service/services.yaml
- service/ingresses.yaml
- config/configmap/workflow-controller-configmap.yaml
- config/secret/oauth2-client.yaml
- workloads/deployments/argo-server.yaml
- workloads/deployments/workflow-controller.yaml

images:
- name: quay.io/argoproj/argocli
  newName: registry.cn-guangzhou.aliyuncs.com/kube-image-repo/argocli
  newTag: v3.5.7
- name: quay.io/argoproj/workflow-controller
  newName: registry.cn-guangzhou.aliyuncs.com/kube-image-repo/argo-workflow-controller
  newTag: v3.5.7
