eventBus:
  nats:
    versions:
    - version: 0.22.1
      natsStreamingImage: registry.cn-hangzhou.aliyuncs.com/kube-image-repo/nats-streaming:0.22.1
      metricsExporterImage: registry.cn-hangzhou.aliyuncs.com/kube-image-repo/prometheus-nats-exporter:0.8.0
  jetstream:
    # Default JetStream settings, could be overridden by EventBus JetStream specs
    settings: |
      # https://docs.nats.io/running-a-nats-service/configuration#jetstream
      # Only configure "max_memory_store" or "max_file_store", do not set "store_dir" as it has been hardcoded.
      # e.g. 1G. -1 means no limit, up to 75% of available memory
      max_memory_store: -1
      # e.g. 20G. -1 means no limit, Up to 1TB if available
      max_file_store: 1TB
    streamConfig: |
      # The default properties of the streams to be created in this JetStream service
      maxMsgs: 50000
      maxAge: 168h
      maxBytes: -1
      replicas: 3
      duplicates: 300s
    versions:
    - version: latest
      natsImage: registry.cn-hangzhou.aliyuncs.com/kube-image-repo/nats:2.10.10
      metricsExporterImage: registry.cn-hangzhou.aliyuncs.com/kube-image-repo/prometheus-nats-exporter:0.14.0
      configReloaderImage: registry.cn-hangzhou.aliyuncs.com/kube-image-repo/nats-server-config-reloader:0.14.0
      startCommand: /nats-server
    - version: 2.10.10
      natsImage: registry.cn-hangzhou.aliyuncs.com/kube-image-repo/nats:2.10.10
      metricsExporterImage: registry.cn-hangzhou.aliyuncs.com/kube-image-repo/prometheus-nats-exporter:0.14.0
      configReloaderImage: registry.cn-hangzhou.aliyuncs.com/kube-image-repo/nats-server-config-reloader:0.14.0
      startCommand: /nats-server
